openapi: 3.0.0
info:
  title: Synkronus API
  version: 1.0.0
paths:
  /version:
    get:
      summary: Get server version and system information
      description: Returns detailed version information about the server, including build information and system details
      responses:
        '200':
          description: Successful response with version information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemVersionInfo'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  $ref: './app-bundle.yaml#/paths'

  $ref: './auth.yaml#/paths'
  $ref: './users.yaml#/paths'

  $ref: './sync.yaml#/paths'

components:
  schemas:
    SystemVersionInfo:
      type: object
      properties:
        server:
          $ref: '#/components/schemas/ServerInfo'
        database:
          $ref: '#/components/schemas/DatabaseInfo'
        system:
          $ref: '#/components/schemas/SystemInfo'
        build:
          $ref: '#/components/schemas/BuildInfo'
    ServerInfo:
      type: object
      properties:
        version:
          type: string
          example: "1.0.0"
    DatabaseInfo:
      type: object
      properties:
        type:
          type: string
          example: "PostgreSQL"
        version:
          type: string
          example: "15.3"
        database_name:
          type: string
          example: "synkronus_db"
    SystemInfo:
      type: object
      properties:
        os:
          type: string
          example: "linux"
        architecture:
          type: string
          example: "amd64"
        cpus:
          type: integer
          example: 4
    BuildInfo:
      type: object
      properties:
        commit:
          type: string
          example: "a1b2c3d4e5f6"
        build_time:
          type: string
          example: "2023-01-01T12:00:00Z"
        go_version:
          type: string
          example: "go1.20.1"
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Failed to get version information"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'JWT token obtained from /auth/login'

  schemas:


    ProblemDetail:
      type: object
      required: [type, title, status, detail]
      properties:
        type:
          type: string
          format: uri
          description: A URI reference that identifies the problem type
          example: "https://example.com/problems/validation-error"
        title:
          type: string
          description: A short, human-readable summary of the problem type
          example: "Validation Error"
        status:
          type: integer
          description: The HTTP status code
          example: 400
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem
          example: "Invalid request format"
        instance:
          type: string
          format: uri
          description: A URI reference that identifies the specific occurrence of the problem
          example: "/problems/validation-error/12345"
        errors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              message:
                type: string
          description: Validation errors for specific fields

