# Example docker-compose.yml for local development/testing
# For production deployment on Coolify, use environment variables directly

version: '3.8'

services:
  synkronus:
    build: .
    ports:
      - "8080:8080"
    environment:
      # Server configuration
      PORT: "8080"
      LOG_LEVEL: "info"
      
      # Database configuration
      DB_CONNECTION: "postgres://synkronus_user:your_password@postgres:5432/synkronus?sslmode=disable"
      
      # JWT Secret (MUST be changed in production!)
      JWT_SECRET: "your-secret-jwt-key-change-this-in-production"
      
      # Admin credentials (optional, will use defaults if not set)
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "change-this-password"
      
      # App bundle storage path (inside container)
      APP_BUNDLE_PATH: "/app/data/app-bundles"
      
      # Maximum number of app bundle versions to keep
      MAX_VERSIONS_KEPT: "5"
    
    volumes:
      # Persistent volume for app bundles
      - app-bundles:/app/data/app-bundles
    
    depends_on:
      - postgres
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: synkronus
      POSTGRES_USER: synkronus_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U synkronus_user -d synkronus"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  app-bundles:
